import pool from "../db/pool";

export interface Channel {
  id: number;
  user_id: number;
  name: string;
  avatar: string;
  subscribers: number;
  verified: boolean;
  created_at: Date;
}

export const createChannelsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS channels (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      name VARCHAR(100) NOT NULL,
      avatar TEXT NOT NULL,
      subscribers INTEGER DEFAULT 0,
      verified BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
};
