import pool from "../db/pool";

export interface Comment {
  id: number;
  user_id: number;
  video_id: number;
  text: string;
  likes: number;
  dislikes: number;
  created_at: Date;
}

export const createCommentsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS comments (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
      text TEXT NOT NULL,
      likes INTEGER DEFAULT 0,
      dislikes INTEGER DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
};
