import pool from "../db/pool";

export interface CommentInteraction {
  id: number;
  user_id: number;
  comment_id: number;
  is_liked: boolean;
  is_disliked: boolean;
  created_at: Date;
}

export const createCommentInteractionsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS comment_interactions (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,
      is_liked BOOLEAN DEFAULT FALSE,
      is_disliked BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, comment_id)
    )
  `);
};
