import pool from "../db/pool";

export interface Subscription {
  id: number;
  user_id: number;
  channel_id: number;
  created_at: Date;
}

export const createSubscriptionsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS subscriptions (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      channel_id INTEGER REFERENCES channels(id) ON DELETE CASCADE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, channel_id)
    )
  `);
};
