import pool from "../db/pool";

export interface SubscriptionHistory {
  id: number;
  user_id: number;
  channel_id: number;
  action: "subscribed" | "unsubscribed";
  created_at: Date;
}

export const createSubscriptionHistoryTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS subscription_history (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      channel_id INTEGER REFERENCES channels(id) ON DELETE CASCADE,
      action VARCHAR(12) NOT NULL CHECK (action IN ('subscribed', 'unsubscribed')),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `);
};
