import pool from "../db/pool";

export interface Video {
  id: number;
  channel_id: number;
  category_id: number | null;
  title: string;
  description: string | null;
  thumbnail_key: string | null;
  duration: number | null;
  views: number;
  likes: number;
  status: "uploading" | "processing" | "ready" | "failed";
  processed_filename: string | null;
  original_filename: string;
  created_at: Date;
  error_message?: string | null;
}

export const createVideosTable = async () => {
  // 1) Ensure full-text and trigram extensions are available
  await pool.query(`
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS unaccent;
  `);

  // 2) Create the videos table (with generated TSVECTOR column)
  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.videos (
      id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      channel_id          INTEGER NOT NULL
                          REFERENCES public.channels(id) ON DELETE CASCADE,
      category_id         INTEGER
                          REFERENCES public.categories(id) ON DELETE SET NULL,
      title               VARCHAR(255) NOT NULL,
      description         TEXT,
      thumbnail           VARCHAR(255),
      views               INTEGER    DEFAULT 0,
      status              VARCHAR(20) DEFAULT 'uploading',
      created_at          TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
      processed_filename  TEXT,
      original_filename   TEXT       NOT NULL,
      error_message       TEXT,
      duration            DOUBLE PRECISION,
      likes               INTEGER    DEFAULT 0,
      title_tsvector      TSVECTOR   GENERATED ALWAYS AS (
                             to_tsvector('english', title)
                           ) STORED
    );
  `);

  // 3) Create a GIN index on title_tsvector for fast full‑text search
  await pool.query(`
    CREATE INDEX IF NOT EXISTS videos_title_tsv_idx
      ON public.videos USING GIN (title_tsvector);
  `);

  // (Optional) If you’ll also query text with trigram similarity, you can add:
  // await pool.query(\`
  //   CREATE INDEX IF NOT EXISTS videos_title_trgm_idx
  //     ON public.videos USING GIN (title gin_trgm_ops);
  // \`);
};
