import pool from "../db/pool";

export interface VideoView {
  id: number;
  user_id: number;
  video_id: number;
  created_at: Date;
}

export const createVideoViewsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS video_views (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, video_id)
    )
  `);
};
