import pool from "../db/pool";

export interface Video {
  id: number;
  channel_id: number;
  category_id: number | null;
  title: string;
  description: string | null;
  thumbnail_key: string | null;
  duration: number | null;
  views: number;
  likes: number;
  status: "uploading" | "processing" | "ready" | "failed";
  processed_filename: string | null;
  original_filename: string;
  created_at: Date;
  error_message?: string | null;
}

export const createVideosTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS videos (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
      category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
      title VARCHAR(255) NOT NULL,
      description TEXT,
      thumbnail_key TEXT,
      duration DOUBLE PRECISION,
      views INTEGER DEFAULT 0,
      status VARCHAR(20) DEFAULT 'uploading',
      processed_filename TEXT,
      original_filename TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      error_message TEXT,
      likes INTEGER DEFAULT 0
    );
  `);
};
