import pool from "../db/pool";

export interface VideoInteraction {
  id: number;
  user_id: number;
  video_id: number;
  is_liked: boolean;
  is_saved: boolean;
  created_at: Date;
}

export const createVideoInteractionsTable = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS video_interactions (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      video_id INTEGER REFERENCES videos(id) ON DELETE CASCADE,
      is_liked BOOLEAN DEFAULT FALSE,
      is_saved BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, video_id)
    )
  `);
};
